version: '3.8'

services:
  ecommerce-container:
    image: postgres
    container_name: ecommerce-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ecommerce_data:
    name: ecommerce_data
